force_keyboard_focus = true
selection_wrap = true
theme = "default"

[placeholders]
"default" = { input = "ï€‚ Search...", list = "No results" }

[providers]
default = [
  "desktopapplications",
  "menus",
  "websearch"
]

[[providers.prefixes]]
prefix = "/"
provider = "providerlist"

[[providers.prefixes]]
prefix = "."
provider = "files"

[[providers.prefixes]]
prefix = ":"
provider = "symbols"

[[providers.prefixes]]
prefix = "="
provider = "calc"

[[providers.prefixes]]
prefix = "@"
provider = "websearch"
